server:
  port: 8080

inception:
  debug: true

  application:
    data-source:
      class-name: org.h2.jdbcx.JdbcDataSource
      url: jdbc:h2:mem:application;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
      min-pool-size: 5
      max-pool-size: 10

spring:
  application:
    name: demo-web
  mail:
    default-encoding: UTF-8
    protocol: smtp
    host: localhost
    port: 2500
    username: demo
    password: demo

