application:

  database:
    dataSource: org.h2.jdbcx.JdbcDataSource
    url: jdbc:h2:mem:application;MODE=DB2;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    minPoolSize: 5
    maxPoolSize: 10

  database-sql-server:
    dataSource: com.microsoft.sqlserver.jdbc.SQLServerXADataSource
    url: jdbc:sqlserver://192.168.185.130:1433;databaseName=Sample;user=Sample;password=Password1
    minPoolSize: 5
    maxPoolSize: 10

  cacheManager:
    cluster:
      port: 15000
      name: test-cluster
      password: YROTLEYO6Z05WAXbCuK4
      members:
    caches:
      - cache:
        name: test-cache
        maxSizePolicy: PER_NODE
        maxSize: 10000
        inMemoryFormat: OBJECT
        evictionPolicy: LRU
        statisticsEnabled: true
        maxIdleSeconds: 300
        backupCount: 0
        asyncBackupCount: 0
        readBackupData: false

  messaging:
    encryptionKey: m/4Wu7iHTCBVu0Bb1JojAhzWQtA5cWIzbWY2YjhmOGE=
    processingRetryDelay: 60000
    maximumProcessingAttempts: 1000

  sms:
    myMobileAPIEndPoint: http://www.mymobileapi.com/api5/api.asmx
    myMobileAPIUsername: XXX
    myMobileAPIPassword: XXX
    maximumSendAttempts: 100
    sendRetryDelay: 600000

---
spring:
    profiles: development

---
spring:
    profiles: production
