#debug: false

server:
  cors:
    allowCredentials: false
    allowedOrigins: http://localhost:4200,http://localhost:8080,http://localhost:20000
    allowedHeaders: "*"
    allowedMethods: "*"
    exposedHeaders: Content-Length, X-Total-Count
    maxAge: 3600

  enableCORS: true

  port: 8080

  security:
    enabled: true
    port: 8443
    keyStore:
      type: JKS
      path: classpath:META-INF/Sample.jks
      alias: Sample
      password: Sample
    trustStore:
      type: JKS
      path: classpath:META-INF/Sample.jks
      password: Sample
    clientAuthMode: required


application:
  database:
    dataSource: org.h2.jdbcx.JdbcDataSource
    url: jdbc:h2:mem:application;MODE=DB2;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    minPoolSize: 5
    maxPoolSize: 10
    packagesToScanForEntities: digital.inception.sample
    inMemoryDatabaseInitResources: digital/inception/sample/inception-sample-h2.sql

  database-postgresql:
    dataSource: org.postgresql.jdbc3.Jdbc3SimpleDataSource
    url: jdbc:postgresql://localhost:5432/sample
    username: sample
    password: Password1
    minPoolSize: 5
    maxPoolSize: 10
    packagesToScanForEntities: digital.inception.sample

  database-sql-server:
    dataSource: com.microsoft.sqlserver.jdbc.SQLServerXADataSource
    url: jdbc:sqlserver://192.168.185.130:1433;databaseName=Sample;user=Sample;password=Password1
    minPoolSize: 5
    maxPoolSize: 10
    packagesToScanForEntities: digital.inception.sample

  security:
    keyStore:
      type: JKS
      path: classpath:META-INF/Sample.jks
      alias: Sample
      password: Sample
    trustStore:
      type: JKS
      path: classpath:META-INF/Sample.jks
      password: Sample


inception:
  cache:
    hazelcast:
      server:
        enabled: true
        cluster:
          port: 15000
          name: sample-cluster
          password: YROTLEYO6Z05WAXbCuK4
          members:
        caches:
          - cache:
            name: sample-cache
            maxSizePolicy: PER_NODE
            maxSize: 10000
            inMemoryFormat: OBJECT
            evictionPolicy: LRU
            statisticsEnabled: true
            maxIdleSeconds: 300
            backupCount: 0
            asyncBackupCount: 0
            readBackupData: false

  messaging:
    encryptionKey: m/4Wu7iHTCBVu0Bb1JojAhzWQtA5cWIzbWY2YjhmOGE=
    processingRetryDelay: 60000
    maximumProcessingAttempts: 1000

  #
  # NOTE: To generate an RSA key-pair to sign JWTs, use the following commands:
  #
  #           openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -pkeyopt rsa_keygen_pubexp:65537 | openssl pkcs8 -topk8 -nocrypt -outform pem > rsa-2048-private-key.p8
  #
  #           openssl pkey -pubout -inform pem -outform pem -in rsa-2048-private-key.p8 -out rsa-2048-public-key.p8
  oauth2:
    authorizationserver:
      jwt:
        private-key-location: classpath:security/oauth2-jwt-key
        public-key-location: classpath:security/oauth2-jwt-key.pub

  sms:
    myMobileAPIEndPoint: http://www.mymobileapi.com/api5/api.asmx
    myMobileAPIUsername: XXX
    myMobileAPIPassword: XXX
    maximumSendAttempts: 100
    sendRetryDelay: 600000


spring:
  mail:
    default-encoding: UTF-8
    protocol: smtp
    host: localhost
    port: 2500
    username: inception
    password: inception
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:security/oauth2-jwt-key.pub

---
spring:
    profiles: development


---
spring:
    profiles: production



#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#    test-connection: false